version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: templateshare
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: