---
# T-SHARE Application Common Configuration

# Application settings
app_name: t-share
app_user: t-share
app_group: "{{ app_user }}"
app_dir: /opt/t-share
data_dir: /mnt/data

# Git repository settings
git_repo_url: https://github.com/ytx/t_share.git
# For private repository, use token-based URL:
# git_repo_url: "https://{{ github_token }}@github.com/ytx/t_share.git"

# Docker settings
docker_compose_file: "{{ app_dir }}/docker-compose.prod.yml"

# SSL/TLS settings
ssl_cert_dir: /etc/ssl/certs/t-share
ssl_cert_file: "{{ ssl_cert_dir }}/server.crt"
ssl_ca_file: "{{ ssl_cert_dir }}/ca.crt"
ssl_key_file: "{{ ssl_cert_dir }}/nopass.key"

# SSL certificate source paths (local)
ssl_cert_source_dir: "~/valut/certs/trusted-host.online/cur"
ssl_cert_source_file: "{{ ssl_cert_source_dir }}/server.crt"
ssl_ca_source_file: "{{ ssl_cert_source_dir }}/ca.crt"
ssl_key_source_file: "{{ ssl_cert_source_dir }}/nopass.key"

# Database settings (common)
postgres_version: "15"
db_user: t_share_user
db_name: t_share_db
db_data_dir: "{{ data_dir }}/postgresql"

# Memory optimization settings (2GB total memory)
# PostgreSQL memory settings (conservative for more Node.js memory)
postgres_shared_buffers: "128MB"
postgres_work_mem: "4MB"
postgres_maintenance_work_mem: "64MB"
postgres_effective_cache_size: "512MB"

# Node.js memory settings (increased for build processes)
node_max_memory: "1024m"

# Nginx settings
nginx_worker_processes: 2
nginx_worker_connections: 1024
nginx_client_max_body_size: "20m"

# System settings
swap_file_size: "1G"
swap_file_path: "{{ data_dir }}/swapfile"

# Log settings
log_dir: "{{ data_dir }}/logs"
log_rotation_days: 7