---
all:
  children:
    staging:
      hosts:
        t-share9.trusted-host.online:
          ansible_host: t-share9.trusted-host.online
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/valut/ssh/4each.pem
    production:
      hosts:
        t-share0.trusted-host.online:
          ansible_host: t-share0.trusted-host.online
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/valut/ssh/4each.pem
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_become: yes
    ansible_become_method: sudo
    allow_world_readable_tmpfiles: true